
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Image as ImageIcon } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../components/Button";
import Card from "../components/Card";
import { screeningApi, toAbsoluteUrl } from "../services/api";

export default function ImageQuality() {
  const { patientId: caseId } = useParams();
  const navigate = useNavigate();
  const [screening, setScreening] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    screeningApi.get(caseId)
      .then(({ data }) => setScreening(data))
      .catch(err => setError(err.response?.data?.detail || "Unable to load screening."));
  }, [caseId]);

  const continueToAI = () => navigate(`/screening/${caseId}`);

  return (
    <div className="page">
      <div className="page-title">
        <div>
          <div className="eyebrow">STEP 3 OF 5 · IMAGE QUALITY</div>
          <h1>Quality check</h1>
          <p className="muted">Quality metrics are generated by the retinal image-processing pipeline during AI screening.</p>
        </div>
        <span className="badge warning large">AI quality check</span>
      </div>

      {error && <div className="auth-error">{error}</div>}

      <div className="quality-grid">
        {["OD", "OS"].map(eye => {
          const image = screening?.images?.[eye];
          const quality = screening?.quality;
          return (
            <Card key={eye} title={eye === "OD" ? "Right eye" : "Left eye"} subtitle={image ? "Image uploaded" : "No image uploaded"}>
              <div className="fundus-placeholder">
                {image ? (
                  <img
                    src={toAbsoluteUrl(image.file_url)}
                    alt={`${eye} fundus`}
                    style={{width:"100%",height:"100%",objectFit:"contain"}}
                  />
                ) : <ImageIcon size={40}/>}
                <span className="image-label">{image?.original_filename || "NOT UPLOADED"}</span>
              </div>
              <div className="quality-metrics">
                <span>Blur <b>{quality?.blur_score ?? "Pending"} {quality?.blur_status || ""}</b></span>
                <span>Brightness <b>{quality?.brightness_score ?? "Pending"} {quality?.brightness_status || ""}</b></span>
                <span>FOV <b>{quality?.fov_ratio ?? "Pending"} {quality?.fov_status || ""}</b></span>
                <span>Visibility <b>{quality?.visibility_ratio ?? "Pending"} {quality?.visibility_status || ""}</b></span>
                <span>Status <b>{quality?.final_status || "Run AI screening"}</b></span>
              </div>
            </Card>
          );
        })}
      </div>

      <div className="info-banner">
        <CheckCircle2 size={19}/>
        <div><strong>Quality is checked during AI screening</strong><span>A rejected image must be recaptured before a diabetic retinopathy prediction can run.</span></div>
      </div>

      <div className="form-actions">
        <Button variant="secondary" onClick={() => navigate(`/capture/${caseId}`)}>
          <ArrowLeft size={17}/> Back
        </Button>
        <Button onClick={continueToAI}>
          Continue to AI screening <ArrowRight size={17}/>
        </Button>
      </div>
    </div>
  );
}
