
import { useEffect, useState } from "react";
import { ArrowRight, BrainCircuit, CheckCircle2, Info, AlertTriangle } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../components/Button";
import Card from "../components/Card";
import { screeningApi } from "../services/api";

export default function ScreeningResult() {
  const { patientId: caseId } = useParams();
  const navigate = useNavigate();
  const [screening, setScreening] = useState(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    screeningApi.get(caseId)
      .then(({ data }) => setScreening(data))
      .catch(err => setError(err.response?.data?.detail || "Unable to load screening."))
      .finally(() => setLoading(false));
  }, [caseId]);

  const runAI = async () => {
    const eye = screening?.images?.OD ? "OD" : screening?.images?.OS ? "OS" : null;
    if (!eye) {
      setError("Upload at least one fundus image first.");
      return;
    }

    setRunning(true);
    setError("");

    try {
      const { data } = await screeningApi.analyze(caseId, eye);
      setScreening(data);
    } catch (err) {
      setError(err.response?.data?.detail || "AI screening failed.");
    } finally {
      setRunning(false);
    }
  };

  if (loading) return <div className="page"><Card><p className="muted">Loading screening...</p></Card></div>;

  const ai = screening?.ai_prediction;
  const confidence = ai?.confidence ?? 0;
  const grade = ai?.dr_grade;
  const hasResult = grade !== null && grade !== undefined;

  return (
    <div className="page">
      <div className="page-title">
        <div>
          <div className="eyebrow">STEP 4 OF 5 · AI SCREENING</div>
          <h1>Screening result</h1>
          <p className="muted">Case <strong>{caseId}</strong>. AI output is decision support, not a standalone diagnosis.</p>
        </div>
        <span className={`badge ${hasResult ? "warning" : "success"} large`}>
          {hasResult ? <><AlertTriangle size={16}/> {ai.severity_name || "Result ready"}</> : "Ready"}
        </span>
      </div>

      {error && <div className="auth-error">{error}</div>}

      {!hasResult ? (
        <Card title="Run AI screening" subtitle="The real retinal quality, prediction, Grad-CAM, and lesion-evidence pipeline will process the stored image.">
          <p className="muted">Uploaded images are already stored. Low-quality images stop before disease prediction and must be recaptured.</p>
          <Button onClick={runAI} disabled={running}>
            <BrainCircuit size={17}/>{running ? "Running..." : "Run AI screening"}
          </Button>
        </Card>
      ) : (
        <>
          <div className="result-grid">
            <Card title="AI assessment">
              <div className="risk-score">
                <div className="score-ring">
                  <strong>{Math.round(confidence * 100)}</strong><span>/ 100</span>
                </div>
                <div>
                  <span className="eyebrow">DR GRADE {grade}</span>
                  <h2>{ai.severity_name}</h2>
                  <p>{ai.recommendation}</p>
                </div>
              </div>
              <div className="probability">
                <div><span>Model confidence</span><strong>{ai.confidence_percent || `${Math.round(confidence*100)}%`}</strong></div>
                <div className="bar"><i style={{width:`${confidence*100}%`}} /></div>
              </div>
            </Card>

            <Card title="Clinical summary">
              <div className="summary-list">
                <div><CheckCircle2/><span>Image stored successfully in the screening case</span></div>
                <div><BrainCircuit/><span>Prediction generated by: {ai.model_status}</span></div>
                <div><Info/><span>Risk level: {ai.risk || "Unavailable"}</span></div>
              </div>
              {ai.doctor_review_required && <div className="notice"><strong>Doctor/Ophthalmologist Review Required</strong><p>AI output is decision support and must not be treated as the final medical diagnosis.</p></div>}
              <div className="notice"><strong>Important</strong><p>This result is not a diagnosis. A qualified clinician should make the final determination.</p></div>
            </Card>
          </div>

          <Card title="Next step" subtitle="Inspect model evidence before clinician review."
            actions={<Button onClick={() => navigate(`/explainability/${caseId}`)}>View explainability <ArrowRight size={17}/></Button>}>
            <p className="muted">Inspect the generated Grad-CAM and AI-generated lesion evidence before clinician review.</p>
          </Card>
        </>
      )}
    </div>
  );
}
